package com.softusing.joe.mapper;

import com.softusing.joe.domain.UserLogin;
import com.softusing.joe.domain.UserLoginExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    long countByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int deleteByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int insert(UserLogin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int insertSelective(UserLogin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    List<UserLogin> selectByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    UserLogin selectByPrimaryKey(Long id);

    List<UserLogin> selectByUserPassword(String password);

    List<UserLogin> selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int updateByExampleSelective(@Param("row") UserLogin row, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int updateByExample(@Param("row") UserLogin row, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int updateByPrimaryKeySelective(UserLogin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    int updateByPrimaryKey(UserLogin row);


}