package com.softusing.joe.domain;

public class UserLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.id
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.username
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.password
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.phone
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.email
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.id
     *
     * @return the value of userlogin.id
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.id
     *
     * @param id the value for userlogin.id
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.username
     *
     * @return the value of userlogin.username
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.username
     *
     * @param username the value for userlogin.username
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.password
     *
     * @return the value of userlogin.password
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.password
     *
     * @param password the value for userlogin.password
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.phone
     *
     * @return the value of userlogin.phone
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.phone
     *
     * @param phone the value for userlogin.phone
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.email
     *
     * @return the value of userlogin.email
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.email
     *
     * @param email the value for userlogin.email
     *
     * @mbg.generated Tue May 16 16:03:55 JST 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }
}